//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./SendStockDataTool_types');
//HELPER FUNCTIONS AND STRUCTURES

SendStockDataTool_sendStockData_args = function(args) {
  this.length = null;
  if (args) {
    if (args.length !== undefined) {
      this.length = args.length;
    }
  }
};
SendStockDataTool_sendStockData_args.prototype = {};
SendStockDataTool_sendStockData_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.length = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendStockDataTool_sendStockData_args.prototype.write = function(output) {
  output.writeStructBegin('SendStockDataTool_sendStockData_args');
  if (this.length !== null && this.length !== undefined) {
    output.writeFieldBegin('length', Thrift.Type.STRING, 1);
    output.writeString(this.length);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SendStockDataTool_sendStockData_result = function(args) {
};
SendStockDataTool_sendStockData_result.prototype = {};
SendStockDataTool_sendStockData_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendStockDataTool_sendStockData_result.prototype.write = function(output) {
  output.writeStructBegin('SendStockDataTool_sendStockData_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SendStockDataToolClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
SendStockDataToolClient.prototype = {};
SendStockDataToolClient.prototype.sendStockData = function(length, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_sendStockData(length);
};

SendStockDataToolClient.prototype.send_sendStockData = function(length) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('sendStockData', Thrift.MessageType.CALL, this.seqid);
  var args = new SendStockDataTool_sendStockData_args();
  args.length = length;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SendStockDataToolClient.prototype.recv_sendStockData = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SendStockDataTool_sendStockData_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
SendStockDataToolProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
SendStockDataToolProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

SendStockDataToolProcessor.prototype.process_sendStockData = function(seqid, input, output) {
  var args = new SendStockDataTool_sendStockData_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.sendStockData(args.length, function (err, result) {
    var result = new SendStockDataTool_sendStockData_result((err != null ? err : {success: result}));
    output.writeMessageBegin("sendStockData", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

